### ISSUE TITLE
win上跑mihomo裸核的配置

### ISSUE THREAD

**Issue by ypxun** [DustinWin/dustinwin.github.io#57]
看了佬在你的博客里写的这篇：[分享 mihomo for Windows 采用 ruleset 方案的一套配置](https://proxy-tutorials.dustinwin.top/posts/share-windows-mihomo-ruleset/)
对于`dns`部分有疑问
```
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  fake-ip-range: 198.18.0.1/16
  enhanced-mode: fake-ip
  fake-ip-filter: ['rule-set:fakeip-filter,private,cn']
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  direct-nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
```
我看你没写海外dns解析，想问下海外域名会如何解析？也使用阿里和腾讯的doh不会导致错误吗？
